In [1]:
import numpy as np
#starting a basic function
# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))
    

        

In [16]:
nonlin(2,0)

0.8807970779778823

In [2]:
# input dataset
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])
    

In [22]:
# output dataset            
y = np.array([[0,0,1,1]]).T


In [23]:
y

array([[0],
       [0],
       [1],
       [1]])

In [4]:
# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)


In [17]:
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1


In [18]:
syn0

array([[-0.39533485],
       [-0.70648822],
       [-0.81532281]])

In [ ]:
for iter in range(10000):

    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))

    # how much did we miss?
    l1_error = y - l1

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)

    # update weights
    syn0 += np.dot(l0.T,l1_delta)
    
print ("Output After Training:")
print (l1)


In [36]:
l1_delta

array([[-1.49917306e-07],
       [-9.99222140e-08],
       [ 6.66093673e-08],
       [ 9.99406204e-08]])